"""Incident report generation using Jinja2 templates."""
from datetime import datetime
from jinja2 import Template
from shared.schemas.events import Incident
from shared.utils.logging import get_logger

logger = get_logger(__name__)

TECHNICAL_REPORT_TEMPLATE = """
# Incident Report: {{ incident.incident_id }}

**Generated:** {{ now }}
**Status:** {{ incident.status }}
**Severity:** {{ incident.severity.value | upper }}
**Confidence:** {{ incident.confidence }}%
**Risk Score:** {{ incident.risk_score }}

---

## Summary

**Attack Type:** {{ incident.attack_type }}
{{ incident.description }}

## Affected Assets

{% for asset in incident.affected_assets %}
- {{ asset }}
{% endfor %}

## Affected Users

{% for user in incident.affected_users %}
- {{ user }}
{% endfor %}

## MITRE ATT&CK Techniques

{% for technique in incident.mitre_techniques %}
- {{ technique }}
{% endfor %}

## Evidence

{% for item in incident.evidence %}
- {{ item }}
{% endfor %}

## Attack Timeline

| Timestamp | Event | Description | Severity |
|-----------|-------|-------------|----------|
{% for entry in incident.timeline %}
| {{ entry.timestamp }} | {{ entry.event }} | {{ entry.description }} | {{ entry.severity }} |
{% endfor %}

## Recommended Actions

{% for action in incident.recommended_actions %}
1. {{ action }}
{% endfor %}

---
*Report generated by SentinelAI Autonomous SOC Analyst*
"""

EXECUTIVE_REPORT_TEMPLATE = """
# Executive Security Briefing

**Date:** {{ now }}
**Incident ID:** {{ incident.incident_id }}
**Risk Level:** {{ incident.severity.value | upper }}

## Key Findings

A **{{ incident.attack_type }}** incident has been detected with **{{ incident.confidence }}%** confidence.

**{{ incident.affected_assets | length }}** assets and **{{ incident.affected_users | length }}** users are affected.

## Business Impact

Risk Score: **{{ incident.risk_score }}/100**

## Immediate Actions Required

{% for action in incident.recommended_actions %}
- {{ action }}
{% endfor %}

---
*SentinelAI - Confidential*
"""


class ReportGenerator:
    def generate_technical_report(self, incident: Incident) -> str:
        template = Template(TECHNICAL_REPORT_TEMPLATE)
        return template.render(incident=incident, now=datetime.utcnow().isoformat())

    def generate_executive_report(self, incident: Incident) -> str:
        template = Template(EXECUTIVE_REPORT_TEMPLATE)
        return template.render(incident=incident, now=datetime.utcnow().isoformat())
