from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, Any
from enum import Enum
import uuid


class LogSource(str, Enum):
    FIREWALL = "firewall"
    ENDPOINT = "endpoint"
    CLOUD = "cloud"
    IDENTITY = "identity"
    NETWORK = "network"
    APPLICATION = "application"


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class RawLogEvent(BaseModel):
    """Raw log event as ingested from sources."""
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    source: LogSource
    source_ip: Optional[str] = None
    dest_ip: Optional[str] = None
    source_port: Optional[int] = None
    dest_port: Optional[int] = None
    protocol: Optional[str] = None
    user: Optional[str] = None
    hostname: Optional[str] = None
    action: Optional[str] = None
    raw_message: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class NormalizedEvent(BaseModel):
    """Normalized event in common schema."""
    event_id: str
    timestamp: datetime
    source: LogSource
    category: str  # authentication, network, process, file, etc.
    action: str
    outcome: str  # success, failure, unknown
    source_ip: Optional[str] = None
    dest_ip: Optional[str] = None
    source_port: Optional[int] = None
    dest_port: Optional[int] = None
    protocol: Optional[str] = None
    user: Optional[str] = None
    hostname: Optional[str] = None
    process_name: Optional[str] = None
    process_command: Optional[str] = None
    file_path: Optional[str] = None
    domain: Optional[str] = None
    url: Optional[str] = None
    severity: Severity = Severity.INFO
    tags: list[str] = Field(default_factory=list)
    raw_message: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class Detection(BaseModel):
    """A detection/alert generated by the detection engine."""
    detection_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    rule_name: str
    rule_id: str
    severity: Severity
    confidence: float = Field(ge=0, le=100)
    description: str
    source_events: list[str]  # event_ids
    mitre_techniques: list[str] = Field(default_factory=list)
    indicators: dict[str, Any] = Field(default_factory=dict)
    false_positive_probability: float = 0.0


class Incident(BaseModel):
    """An investigated incident."""
    incident_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    title: str
    description: str
    severity: Severity
    status: str = "open"  # open, investigating, contained, resolved, closed
    confidence: float
    attack_type: str
    detections: list[str]  # detection_ids
    affected_assets: list[str] = Field(default_factory=list)
    affected_users: list[str] = Field(default_factory=list)
    mitre_techniques: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    reasoning: list[str] = Field(default_factory=list)
    recommended_actions: list[str] = Field(default_factory=list)
    timeline: list[dict[str, Any]] = Field(default_factory=list)
    risk_score: float = 0.0
    assigned_to: Optional[str] = None
